[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
itertools = "0.14"
serde = "1"
serde_json = "1"
rand = "0.9"
rayon = "1.10"
regex = "1"
